/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityLogsView: typeof import('./../src/components/pages/generador/ActivityLogsView.vue')['default']
    AnimatedLogo: typeof import('./../src/components/svg/AnimatedLogo.vue')['default']
    AppLayout: typeof import('./../src/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./../src/layouts/AuthLayout.vue')['default']
    CameraStream: typeof import('./../src/components/pages/generador/CameraStream.vue')['default']
    ClientOnly: typeof import('./../src/components/ClientOnly.vue')['default']
    ConfigComponentView: typeof import('./../src/components/pages/generador/ConfigComponentView.vue')['default']
    DashboardComponentView: typeof import('./../src/components/pages/generador/DashboardComponentView.vue')['default']
    DashboardsMobileSubsidebar: typeof import('./../src/layouts/mobile-subsidebars/DashboardsMobileSubsidebar.vue')['default']
    DashboardsSubsidebar: typeof import('./../src/layouts/sidebar-subsidebar/DashboardsSubsidebar.vue')['default']
    LandingLayout: typeof import('./../src/layouts/LandingLayout.vue')['default']
    LanguageDropdown: typeof import('./../src/components/LanguageDropdown.vue')['default']
    LanguagesPanel: typeof import('./../src/components/partials/panels/LanguagesPanel.vue')['default']
    MobileNavbar: typeof import('./../src/components/navigation/mobile/MobileNavbar.vue')['default']
    MobileSidebar: typeof import('./../src/components/navigation/mobile/MobileSidebar.vue')['default']
    PrincipalViewComponent: typeof import('./../src/components/pages/generador/PrincipalViewComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/navigation/desktop/Sidebar.vue')['default']
    Toolbar: typeof import('./../src/components/partials/toolbars/Toolbar.vue')['default']
    VAction: typeof import('./../src/components/base/button/VAction.vue')['default']
    VAvatar: typeof import('./../src/components/base/avatar/VAvatar.vue')['default']
    VAvatarStack: typeof import('./../src/components/base/avatar/VAvatarStack.vue')['default']
    VButton: typeof import('./../src/components/base/button/VButton.vue')['default']
    VButtons: typeof import('./../src/components/base/button/VButtons.vue')['default']
    VCheckbox: typeof import('./../src/components/base/form/VCheckbox.vue')['default']
    VCollapseLinks: typeof import('./../src/components/base/collapse-links/VCollapseLinks.vue')['default']
    VControl: typeof import('./../src/components/base/form/VControl.vue')['default']
    VDropdown: typeof import('./../src/components/base/dropdown/VDropdown.vue')['default']
    VField: typeof import('./../src/components/base/form/VField.vue')['default']
    VIcon: typeof import('./../src/components/base/icon/VIcon.vue')['default']
    VIconBox: typeof import('./../src/components/base/icon/VIconBox.vue')['default']
    VIconButton: typeof import('./../src/components/base/button/VIconButton.vue')['default']
    VInput: typeof import('./../src/components/base/form/VInput.vue')['default']
    VLabel: typeof import('./../src/components/base/form/VLabel.vue')['default']
    VLoader: typeof import('./../src/components/base/loader/VLoader.vue')['default']
    VModal: typeof import('./../src/components/base/modal/VModal.vue')['default']
    VPageContent: typeof import('./../src/components/base/layouts/VPageContent.vue')['default']
    VPageContentWrapper: typeof import('./../src/components/base/layouts/VPageContentWrapper.vue')['default']
    VPlaceload: typeof import('./../src/components/base/loader/VPlaceload.vue')['default']
    VPlaceloadAvatar: typeof import('./../src/components/base/loader/VPlaceloadAvatar.vue')['default']
    VPlaceloadText: typeof import('./../src/components/base/loader/VPlaceloadText.vue')['default']
    VPlaceloadWrap: typeof import('./../src/components/base/loader/VPlaceloadWrap.vue')['default']
    VSelect: typeof import('./../src/components/base/form/VSelect.vue')['default']
    VTag: typeof import('./../src/components/base/tags/VTag.vue')['default']
    VViewWrapper: typeof import('./../src/components/base/layouts/VViewWrapper.vue')['default']
  }
}
